---
inputs:
  - type: git
    branch: dual-template
    service: ${DCT_PIPELINE_REPO}
    path: .init_dct_pipeline
  - type: git
    branch: master
    service: ${TEKTON_CATALOG_REPO}
    path: signing/dct
triggers:
  - type: manual
    name: Manual Trigger
    eventListener: dct-listener
properties:
  - name: api-key
    value: ${API_KEY}
    type: SECURE
  - name: revision
    value: master
    type: text
  - name: registry-region
    value: ${REGISTRY_REGION_ID}
    type: text
  - name: app-name
    value: ${APP_NAME}
    type: text
  - name: registry-namespace
    value: ${REGISTRY_NAMESPACE}
    type: text
  - name: dev-cluster-namespace
    value: ${PROD_CLUSTER_NAMESPACE}
    type: text
  - name: dev-region
    value: ${PROD_REGION_ID}
    type: text
  - name: cluster-name
    value: ${PROD_CLUSTER_NAME}
    type: text
  - name: dev-resource-group
    value: ${PROD_RESOURCE_GROUP}
    type: text
  - name: vault-name
    value: ${VAULT_INSTANCE}
    type: text
  - name: validation-signer
    value: ${VALIDATION_SIGNER}
    type: text
  - name: build-signer
    value: ${BUILD_SIGNER}
    type: text
